### ISSUE TITLE
shadow-useragent attempts to write to system-wide site_packages directory (PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/shadow_useragent/data/useragents.pk')

### ISSUE THREAD

**Issue by christophfink** [lobstrio/shadow-useragent#5]
`shadow-useragent` attempts to write its cache to the site-packages directory. This works in user-local and virtualenv installations (even though it’s discouraged) because the user running the script has write permissions in the install path. The same fails entirely if the package is installed system-wide, because the user running the script does not (should not, must not) have write permissions to the install location.

The best practice solution would be to save the cache files to a sub-directory of `$XDG_CACHE_HOME` (works on Linux and Mac, see [this](https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows) stackoverflow question for the equivalents on Windows).

**Comment by lobstrio** [comment]
@christophfink your PR is merged therefore I'm closing this.

Thanks
