### ISSUE TITLE
Server broke down

### ISSUE THREAD

**Issue by 2chfl** [lobstrio/shadow-useragent#9]
http://51.158.74.109/useragents/?format=json

Returns only the server error.

ERROR:shadow-useragent:<html>
<head><title>502 Bad Gateway</title></head>

**Comment by 2chfl** [comment]
504 Gateway Time-out

**Comment by lobstrio** [comment]
@2chfl  api is back up.

We were keeping logs from the incoming request but as the api is getting more success the logs ate up the server memory.

I deactivated the logs so this should not happen again

Thanks for raising
